### ISSUE TITLE
Package return values changed

### ISSUE THREAD

**Issue by sormuras** [CodeFX-org/java-9-wtf#1]
Having a class like `DefaultPackageTestCase` defined in the default package, the result of `DefaultPackageTestCase.class.getPackage()` differ. See following code:

```java
System.out.println("Java version = " + Runtime.class.getPackage().getImplementationVersion());
System.out.println("  class = |" + DefaultPackageTestCase.class + "|");
System.out.println("package = |" + DefaultPackageTestCase.class.getPackage() + "|");
System.out.println("   name = |" + DefaultPackageTestCase.class.getPackage().getName() + "|");
```

**Java 8**

```java
Java version = 1.8.0_121

  class = |class DefaultPackageTestCase|
package = |null|
java.lang.NullPointerException
```

**Java 9**

```java
Java version = null

  class = |class DefaultPackageTestCase|
package = |package |
   name = ||
```

**Comment by AlanBateman** [comment]
The java.lang.Package API has been overhauled for Java SE 9 so that it works with modules. See the javadoc for more on this.

**Comment by nipafx** [comment]
Sooo, @sormuras, up for a PR? :smiley:

**Comment by sormuras** [comment]
I'm with Mikhail here: I inlined _"the test case right here because I believe you have better idea how to integrate it into your compiler module"_

**Comment by nipafx** [comment]
@sormuras: Lazy bum, [happy now](http://java9.wtf/default-package/)? :smiley:

**Comment by sormuras** [comment]
Done via https://github.com/CodeFX-org/java-9-wtf/commit/0a3ac95722e5a0690e99f85aaf4eee857463b528
