### ISSUE TITLE
Eclipse PDE + Tycho MVN

### ISSUE THREAD

**Issue by angel539** [CodeFX-org/java-9-wtf#10]
Hi, 

I am trying to configure my Eclipse plugin to work with update site and mvn following this approach:

http://www.eclipse.org/community/eclipse_newsletter/2013/august/article3.php

I have been looking for solutions for my own issue and I have found your github account talking about this.

The current state of the build section of my parent pom is:

<build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.7.0</version>
        <configuration>
          <compilerId>jdt</compilerId>
          <source>8</source>
          <target>8</target>
          <compilerArgs>
            <arg>-proc:none</arg>
          </compilerArgs>
        </configuration>
        <dependencies>
          <dependency>
              <groupId>org.eclipse.tycho</groupId>
              <artifactId>tycho-compiler-jdt</artifactId>
              <version>1.1.0</version>
          </dependency>
          <dependency>
              <groupId>org.eclipse.tycho</groupId>
              <artifactId>org.eclipse.jdt.core</artifactId>
              <version>3.11.2.v20160212-1500</version>
          </dependency>
        </dependencies>
      </plugin>

      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-maven-plugin</artifactId>
        <version>1.2.0</version>
        <extensions>true</extensions>
        <configuration>
          <encoding>UTF-8</encoding>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-compiler-plugin</artifactId>
        <version>1.2.0</version>
      </plugin>

      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>target-platform-configuration</artifactId>
        <version>1.2.0</version>
        <configuration>
          <resolver>p2</resolver>
          <pomDependencies>consider</pomDependencies>
          <ignoreTychoRepositories>true</ignoreTychoRepositories>
          <environments>
            <environment>
              <os>linux</os>
              <ws>gtk</ws>
              <arch>x86</arch>
            </environment>
            <environment>
              <os>linux</os>
              <ws>gtk</ws>
              <arch>x86_64</arch>
            </environment>
            <environment>
              <os>win32</os>
              <ws>win32</ws>
              <arch>x86</arch>
            </environment>
            <environment>
              <os>win32</os>
              <ws>win32</ws>
              <arch>x86_64</arch>
            </environment>
            <environment>
              <os>macosx</os>
              <ws>cocoa</ws>
              <arch>x86_64</arch>
            </environment>
          </environments>
        </configuration>
      </plugin>
    </plugins>
  </build>

I am working with Eclipse Mars 2 (the whole plugin has been develop in this enviroment) and Java 8. Do you have any clue of what is happening with tycho and why this is not compiling. It is a thing of the versions?

All the best,

Ángel

**Comment by angel539** [comment]
By the way... I am a really newcomer with maven, then, apollogies if something is wrong in the previous message.

**Comment by angel539** [comment]
Solved.

**Comment by nipafx** [comment]
Hi @angel539, I only now have a little time to look into this, but I see you already solved it. :+1:

**Comment by angel539** [comment]
Actually I have another question about this. After uploading my artifacts to Github, I discover how the libs I have dissappeared. And this is because mvn is conceived to manage all the dependencies though the pom files and not only the MANIFEST where the libraries are added to the clashpath. 

Do you know if the dependencies with the other artifacts I have in my project, such as the dependency between the UI and the Core model, have to be added as well to the POM file?

I understand that for every dependency or every mvn resolution I have to add something like:

```xml
  <dependencies>
    <dependency>
      <groupId>GROUP</groupId>
      <artifactId>ARTIFACT</artifactId>
      <version>VERSION</version>
    </dependency>
  </dependencies>
```

With the dependencies that already are in a repository. But I don't know if I have to do the same thing with the dependencies between projects, that in Eclipse PDE are resolved though the MANIFEST.

All the best,

Ángel

**Comment by nipafx** [comment]
> Do you know if the dependencies with the other artifacts I have in my project, such as the dependency between the UI and the Core model, have to be added as well to the POM file?

Yes, Maven needs to know about the dependencies between different artifacts in the same project. At least that's how it usually goes, I have no particular knowledge about writing Eclipse plugins.

Generally speaking, you should ask these question on a Q&A platform like StackOverflow (after searching for existing questions and answers of course) because your problem and a possible solution will be much more visible there.

**Comment by angel539** [comment]
Ok, thanks anyway :)
