### ISSUE TITLE
More Javac compiler issues

### ISSUE THREAD

**Issue by mfursov** [CodeFX-org/java-9-wtf#2]
The code below compiles with Java8 compiler but fails with Java9. I inline the test case right here because I believe you have better idea how to integrate it into your compiler module:

```java
import javax.swing.tree.DefaultMutableTreeNode;
import java.util.List;

public class MyNode extends DefaultMutableTreeNode {

    public int countChildren() {
        return ((List<MyNode>) children).size();
    }

}
```

**Comment by AlanBateman** [comment]
This is source compatibility issue in DefaultMutableTreeNode where the field changed from raw Vector to `Vector<TreeNode>`.

**Comment by nipafx** [comment]
Oops, forgot to subscribe to my own repo, sorry @mfursov. Yes, I've come across that. Feel free to create a PR demonstrating the problem and fix.

**Comment by nipafx** [comment]
I considered including this but decided against it. It is no compiler issue but, as @AlanBateman points out, comes from a very minor API change and I think including those would muddy the waters.

@mfursov Still, thank you very much for opening an issue. Please do so again if you find something.
