### ISSUE TITLE
java-10-wtf

### ISSUE THREAD

**Issue by quentinburley** [CodeFX-org/java-9-wtf#7]
interesting in knowing any news about how the issues from 'java-9-wtf' fare in java-10

**Comment by nipafx** [comment]
I wondered for a while how to handle newer Java versions in this project and now decided that I I won't invest the time into keeping it up to date. I won't renew the domain java9.wtf and won't make any more changes in this project.

If you're interested in maintaining it, feel free to create a fork. 🌻
